function initTask(subTask) {
    subTask.gridInfos = {				//podatki za urejevalnik in vizualno okno
		hideControls: {					//gumbi na urejevalniku
			restart: false,
			saveOrLoad: false,			//gumba za shranjevanje in nalaganje kode ukazov
			loadBestAnswer: false,
			speedSlider: false,
			backToFirst: false,
			nextStep: false,
			goToEnd: false,
		},
		introMaxHeight: "33%",				//maksimalna velikost prostora za navodila
		maxListSize: 100, 						//max. dolžina seznama
		scrollbars: true,
		zoom: {
			controls: true,
			scale: 1,
		},
		actionDelay: 200,						//parameter za časovni zamik med izvajanjem ukazov
		blocklyColourTheme: "bwinf",	//izbira seta barv za bloke ukazov
		maxInstructions:  60,
		includeBlocks: {						//dovoljeni ukazi 
			groupByCategory: true,
			generatedBlocks: {
				robot: ["forward","left","right","writeNumber","numberUnder"],
			},
			standardBlocks: {
				includeAll: false,
				wholeCategories: ["logic","loops","math"],
				singleBlocks: [],
				excludedBlocks: [],
			},
			variables: ["nagrade"],
		},
		startingExample: { //vnaprej podana koda ukazov
			blockly: '',
		},					
		checkEndEveryTurn: false,		//kako pogosto preverjamo uspešnost rešitve
		checkEndCondition: robotEndConditions.checkValueOnGoal,
			  
		cellSide: 60,							
		itemTypes: {
			green_robot: { img: "green_robot.png", category: "robot", side: 80, nbStates: 9, offsetX: -14, zOrder: 8},
			tile: { num: 1, img: "tile.png", side: 60, zOrder: 0 },
			obstacle: { num: 2, img: "obstacle.png", side: 60, category: "obstacle", isObstacle: true, zOrder: 1 },
			//obstacle1: { num: 21, img: "drevo.png", side: 60, category: "obstacle", isObstacle: true, zOrder: 0 },
			green: { num: 3, img: "green.png", side: 60, category: "paint", zOrder: 3, color: "vert" },
			pill: { num: 4, img: "pill.png", side: 60, category: "pill", isCollectible: true, zOrder: 7 },
			hole: { num: 5, img: "hole.png", side: 60, category: "hole", isHole: true, zOrder: 2 },
			marble: { num: 6, img: "marble.png", side: 60, category: "marble", isTransportable: true, zOrder: 6 },
			marker: { num: 7, img: "marker.png", side: 60, category: "marker", isMarker: true, zOrder: 5 },
			paint1: { num: 81, img: "paint1.png", side: 60, category: "paint", isPaint: true, color: "rouge", zOrder: 4 },
			paint2: { num: 82, img: "paint2.png", side: 60, category: "paint", isPaint: true, color: "bleu", zOrder: 4 },
			paint3: { num: 83, img: "paint3.png", side: 60, category: "paint", isPaint: true, color: "vert", zOrder: 4 },
			paint4: { num: 84, img: "paint4.png", side: 60, category: "paint", isPaint: true, color: "jaune", zOrder: 4 },
			0: { num: 100, side: 60, category: "number", value: 0, zOrder: 1 },
			1: { num: 101, side: 60, category: "number", value: 1, zOrder: 1 },
			2: { num: 102, side: 60, category: "number", value: 2, zOrder: 1 },
			3: { num: 103, side: 60, category: "number", value: 3, zOrder: 1 },
			4: { num: 104, side: 60, category: "number", value: 4, zOrder: 1 },
			5: { num: 105, side: 60, category: "number", value: 5, zOrder: 1 },
			6: { num: 106, side: 60, category: "number", value: 6, zOrder: 1 },
			7: { num: 107, side: 60, category: "number", value: 7, zOrder: 1 },
			8: { num: 108, side: 60, category: "number", value: 8, zOrder: 1 },
			9: { num: 109, side: 60, category: "number", value: 9, zOrder: 1 },
			10: { num: 110, side: 60, category: "number", value: 10, zOrder: 1 },
			11: { num: 111, side: 60, category: "number", value: 11, zOrder: 1 },
			12: { num: 112, side: 60, category: "number", value: 12, zOrder: 1 },
			13: { num: 113, side: 60, category: "number", value: 13, zOrder: 1 },
			14: { num: 114, side: 60, category: "number", value: 14, zOrder: 1 },
			15: { num: 115, side: 60, category: "number", value: 15, zOrder: 1 },
			16: { num: 116, side: 60, category: "number", value: 16, zOrder: 1 },
			17: { num: 117, side: 60, category: "number", value: 17, zOrder: 1 },
			18: { num: 118, side: 60, category: "number", value: 18, zOrder: 1 },
			19: { num: 119, side: 60, category: "number", value: 19, zOrder: 1 },
			20: { num: 120, side: 60, category: "number", value: 20, zOrder: 1 },
			21: { num: 121, side: 60, category: "number", value: 21, zOrder: 1 },
			22: { num: 122, side: 60, category: "number", value: 22, zOrder: 1 },
			23: { num: 123, side: 60, category: "number", value: 23, zOrder: 1 },
			24: { num: 124, side: 60, category: "number", value: 24, zOrder: 1 },
			25: { num: 125, side: 60, category: "number", value: 25, zOrder: 1 },
			26: { num: 126, side: 60, category: "number", value: 26, zOrder: 1 },
			27: { num: 127, side: 60, category: "number", value: 27, zOrder: 1 },
			28: { num: 128, side: 60, category: "number", value: 28, zOrder: 1 },
			29: { num: 129, side: 60, category: "number", value: 29, zOrder: 1 },
			30: { num: 130, side: 60, category: "number", value: 30, zOrder: 1 },
			31: { num: 131, side: 60, category: "number", value: 31, zOrder: 1 },
			32: { num: 132, side: 60, category: "number", value: 32, zOrder: 1 },
		}, //isRound, isSquare, isTriangle, isDotted, isFull, isStriped, // hasColor(color) // isTransportable(color, shape) // "paint"(color) //"number"(value)
		ignoreInvalidMoves: false,
	};

	subTask.data = {						//testni primeri
		easy:[
			{
				tiles: [
					[2, 2, 1, 2, 2, 2, 1, 2],
					[2, 1, 1, 1, 2, 1, 1, 2],
					[1, 1, 1, 1, 1, 1, 2, 2],
					[1, 1, 1, 1, 1, 1, 1, 2],
					[1, 1, 2, 2, 1, 1, 1, 1],
					[1, 1, 1, 2, 2, 1, 1, 1],
					[2, 1, 1, 1, 1, 1, 1, 2],
					[2, 2, 1, 1, 1, 1, 2, 2],
				],
				initItems: [
					{ row: 3, col: 0, dir: 0, type: "green_robot" },
					{ row: 3, col: 1, type: 1 },
					{ row: 3, col: 2, type: 2 },
					{ row: 3, col: 4, type: 5 },
					{ row: 3, col: 5, type: 2 },
					{ row: 4, col: 5, type: 1 },
					{ row: 5, col: 5, type: 4 },
					{ row: 6, col: 5, type: 2 },
					{ row: 6, col: 4, type: 2 },
					{ row: 6, col: 2, type: 6 },
					{ row: 6, col: 1, type: 2 },
					{ row: 5, col: 1, type: 3 },
					{ row: 2, col: 1, type: 6 },
					{ row: 1, col: 1, type: 0 },
					{ row: 3, col: 1, type: "paint1" },
					{ row: 3, col: 2, type: "paint2" },
					{ row: 3, col: 4, type: "paint3" },
					{ row: 3, col: 5, type: "paint1" },
					{ row: 4, col: 5, type: "paint2" },
					{ row: 5, col: 5, type: "paint3" },
					{ row: 6, col: 5, type: "paint1" },
					{ row: 6, col: 4, type: "paint2" },
					{ row: 6, col: 2, type: "paint3" },
					{ row: 6, col: 1, type: "paint1" },
					{ row: 5, col: 1, type: "paint2" },
					{ row: 2, col: 1, type: "paint3" },
					{ row: 1, col: 1, type: "paint4" },
				],
			},
			{
				tiles: [
					[2, 1, 1, 1, 1, 1, 1, 2],
					[2, 1, 2, 1, 2, 1, 1, 2],
					[1, 1, 1, 2, 1, 1, 1, 1],
					[1, 1, 1, 2, 1, 1, 1, 1],
					[1, 1, 1, 1, 1, 1, 1, 1],
					[2, 1, 1, 1, 1, 1, 1, 2],
					[2, 1, 1, 1, 1, 1, 2, 2],
					[2, 2, 1, 1, 1, 2, 2, 2],
				],
				initItems: [
					{ row: 3, col: 0, dir: 0, type: "green_robot" },
					{ row: 3, col: 1, type: 3 },
					{ row: 2, col: 1, type: 1 },
					{ row: 1, col: 1, type: 5 },
					{ row: 0, col: 1, type: 2 },
					{ row: 0, col: 2, type: 2 },
					{ row: 0, col: 4, type: 4 },
					{ row: 0, col: 5, type: 2 },
					{ row: 1, col: 5, type: 2 },
					{ row: 3, col: 5, type: 3 },
					{ row: 4, col: 5, type: 2 },
					{ row: 4, col: 4, type: 1 },
					{ row: 4, col: 3, type: 6 },
					{ row: 4, col: 2, type: 3 },
					{ row: 5, col: 2, type: 1 },
					{ row: 6, col: 2, type: 2 },
					{ row: 7, col: 2, type: 0 },
					{ row: 3, col: 1, type: "paint1" },
					{ row: 2, col: 1, type: "paint2" },
					{ row: 1, col: 1, type: "paint3" },
					{ row: 0, col: 1, type: "paint1" },
					{ row: 0, col: 2, type: "paint2" },
					{ row: 0, col: 4, type: "paint3" },
					{ row: 0, col: 5, type: "paint1" },
					{ row: 1, col: 5, type: "paint2" },
					{ row: 3, col: 5, type: "paint3" },
					{ row: 4, col: 5, type: "paint1" },
					{ row: 4, col: 4, type: "paint2" },
					{ row: 4, col: 3, type: "paint3" },
					{ row: 4, col: 2, type: "paint1" },
					{ row: 5, col: 2, type: "paint2" },
					{ row: 6, col: 2, type: "paint3" },
					{ row: 7, col: 2, type: "paint4" },
				],
			},
		],
	};

	initBlocklySubTask(subTask);	//klic programskega orodja Blockly
}

initWrapper(initTask, null, null, true);
//initWrapper(initTask, null, null, true);
