var MSG = {
  title: "Urejevalnik",
  blocks: "Kocke",
  linkTooltip: "Shrani in poveži s kockami.",
  runTooltip: "Zaženi program.",
  badCode: "Napaka v programu:\n%1",
  timeout: "Število iteracij preseženo.",
  trashTooltip: "Zavrži vse kocke.",
  catLogic: "Logika",
  catLoops: "Zanke",
  catMath: "Matematika",
  catText: "Tekst",
  catLists: "Seznam",
  catColour: "Barve",
  catVariables: "Spremenljivke",
  catFunctions: "Funkcije",
  listVariable: "seznam",
  textVariable: "tekst",
  httpRequestError: "Prišlo je do napake pri zahtevi.",
  linkAlert: "Deli kocke s povezavo:\n\n%1",
  hashError: "Oprostite, '%1' ni v povezavi z nobenim shranjenim programom.",
  xmlError: "Shranjene datoteke ni bilo mogoče naložiti. Morda uporablja drugo različico Blockly?",
  badXml: "Napaka v branju XML:\n%1\n\nIzberi 'OK' za opustitev sprememb ali 'Cancel' za urejanje XML."
};
