function initTask(subTask) {
	subTask.gridInfos = {				//podatki za urejevalnik in vizualno okno
		hideControls: {					//gumbi na urejevalniku
			restart: false,
			saveOrLoad: false,			//gumba za shranjevanje in nalaganje kode ukazov
			loadBestAnswer: false,
			speedSlider: false,
			backToFirst: false,
			nextStep: false,
			goToEnd: false,
		},
		introMaxHeight: "33%",				//maksimalna velikost prostora za navodila
		maxListSize: 100, 						//max. dolžina seznama
		scrollbars: true,
		zoom: {
			controls: true,
			scale: 1,
		},
		actionDelay: 200,						//parameter za časovni zamik med izvajanjem ukazov
		blocklyColourTheme: "bwinf",	//izbira seta barv za bloke ukazov
		maxInstructions: 60,
		includeBlocks: {																	//dovoljeni ukazi 
			groupByCategory: true,
			generatedBlocks: {
				turtle: ["moveamount", "turnleftamount", "turnrightamount", "inputvalue"],
			},
			standardBlocks: {
				includeAll: {
					basic: false,
					easy: false, 
					medium: false, 
					hard: true,
				},
				wholeCategories: ["math","functions","variables","logic"],
				singleBlocks: [],
				excludedBlocks: [],
			},
		},
		startingExample: {
			blockly: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="robot_start" id="tZkAx,}bnkHg`k.i)30|" deletable="false" movable="false" editable="false" x="0" y="0"><next><block type="variables_set" id="0,!.v8Ep~VM3YkYB/ib}"><field name="VAR">n</field><value name="VALUE"><block type="inputvalue" id="rWd!]l|Y3QF|g,.8!FHm"></block></value><next><block type="procedures_callnoreturn" id=",B_Cs9p1/BwoE~s91]uV"><mutation name="koch"><arg name="n"></arg><arg name="d"></arg></mutation><value name="ARG0"><block type="variables_get" id="+5jget7FZ4AmakCYn{!7"><field name="VAR">n</field></block></value><value name="ARG1"><block type="math_number" id="3;!;:#/:CmCDM0VVWEFt"><field name="NUM">81</field></block></value></block></next></block></next></block><block type="procedures_defnoreturn" id="!s`|ccmRV}L.tfV4j.[/" x="222" y="0"><mutation><arg name="n"></arg><arg name="d"></arg></mutation><field name="NAME">koch</field><comment pinned="false" h="80" w="160">Opiši to funkcijo...</comment></block></xml>',	
		},
		checkEndEveryTurn: false,													//kako pogosto preverjamo uspešnost rešitve
		checkEndCondition: turtleEndConditions.checkImagesEqual,	//funkcija za preverjanje uspešnosti rešitve
     		
		overlayFileName: "sand.png",
		turtleImageFile: "turtle.png",
		turtleStepSize: 0.3,
		coords : { //max x:300, y:300
			easy: { x: 150, y: 260},
		},
	};

	subTask.data = {					//testni primeri
		easy: [
			{
				inputValue: 4,
				drawSolution: function(turtle) {
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
					turtle.turn(240);
					turtle.move(1);
					turtle.turn(60);
					turtle.move(1);
				},			
			},
			{
				inputValue: 3,
				drawSolution: function(turtle) {
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);
					turtle.turn(240);
					turtle.move(3);
					turtle.turn(60);
					turtle.move(3);					
				},
			},
			{
				inputValue: 2,
				drawSolution: function(turtle) {
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(240);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(240);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(240);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(240);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
					turtle.turn(240);
					turtle.move(9);
					turtle.turn(60);
					turtle.move(9);
				},
			},
			{
				inputValue: 1,
				drawSolution: function(turtle) {
					turtle.move(27);
					turtle.turn(60);
					turtle.move(27);
					turtle.turn(240);
					turtle.move(27);
					turtle.turn(60);
					turtle.move(27);
				},
			},
			{
				inputValue: 0,
				drawSolution: function(turtle) {
					turtle.move(81); 
				},
			},
		],
	};

	initBlocklySubTask(subTask);	//klic programskega orodja Blockly
}

initWrapper(initTask, null, null, true);
//initWrapper(initTask, null, null, true);
